db:
  image: mongo
  ports:
    - "27017:27017"
  restart: always
web:
  build: .
  volumes:
    - ./:/app
  ports:
    - "3001:3001"
  links:
    - db
frontend:
  build: ./frontend
  volumes:
    - ./frontend:/app
    # One-way volume to use node_modules from inside image
    - /app/node_modules
  ports:
    - "3000:3000"
  tty: true
  environment:
    - NODE_ENV=development